### ISSUE TITLE
Setup fails

### ISSUE THREAD

**Issue by corefx** [kcaaj/bdvl#17]
Hello,
I get a following error message after executing sh etc/depinstall.sh && make command.
Tested on Ubuntu 20.04.1 Server. Python version: 3.8.2

python setup.py
Traceback (most recent call last):
  File "setup.py", line 401, in <module>
    INSTALL_DIR = ut.randpath(7)
  File "setup.py", line 362, in randpath
    randdir = choice(listdir(randroot))
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
make: *** [Makefile:12: setup] Error 1

**Comment by kcaaj** [comment]
It is trying to select randomly from nothing. Why is that...?
What is the value of `randroot` before that error? Does whatever `randroot` is even exist on your machine? Do you get this error every attempt?

**Comment by corefx** [comment]
`randroot` is defined on [https://github.com/kcaaj/bdvl/blob/nobash/setup.py](https://github.com/kcaaj/bdvl/blob/nobash/setup.py)
I got a different error when I tried again:

python setup.py
Traceback (most recent call last):
  File "setup.py", line 403, in <module>
    CLEANEDTIME_PATH = ut.randpath(7) if not FILE_CLEANSE_TIMER == None else None
  File "setup.py", line 362, in randpath
    randdir = choice(listdir(randroot))
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
make: *** [Makefile:12: setup] Error 1

I also tested on Ubuntu 16.04.7 (Python 3.5) and got this error:

python setup.py
Traceback (most recent call last):
  File "/usr/lib/python3.5/random.py", line 253, in choice
    i = self._randbelow(len(seq))
  File "/usr/lib/python3.5/random.py", line 230, in _randbelow
    r = getrandbits(k)          # 0 <= r < 2**k
ValueError: number of bits must be greater than zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 403, in <module>
    CLEANEDTIME_PATH = ut.randpath(7) if not FILE_CLEANSE_TIMER == None else None
  File "setup.py", line 362, in randpath
    randdir = choice(listdir(randroot))
  File "/usr/lib/python3.5/random.py", line 255, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
Makefile:11: recipe for target 'setup' failed
make: *** [setup] Error 1

**Comment by kcaaj** [comment]
Thanks. I'll add a check for this to prevent this from happening in future. :fireworks:
